[caddy]
admin_url = "http://127.0.0.1:2020"
http_port = 2800
bind = ["127.0.0.1", "::1"]

[services.s3browser]
hosts = ["s3browser.localhost"]
target_port_env = "S3BROWSER_PORT"

[services.minio]
hosts = ["minios3.localhost", "*.minios3.localhost"]
target_port_env = "MINIO_PORT"

[services.minioconsole]
hosts = ["minioconsole.localhost"]
target_port_env = "MINIO_CONSOLE_PORT"

[services.weed]
enabled = false
hosts = ["weeds3.localhost", "*.weeds3.localhost"]
target_port_env = "WEED_S3_PORT"
